### PR TITLE
Make pytest-workflow git-aware

### PR DESCRIPTION
**Pull request by rhpvorderman**
@DavyCats @Redmar-van-den-Berg , could you please review this? It should reduce the wear and tear on your SSDs significantly :wink:. 

Preliminary testing with Germline-DNA pipeline. Copying everything for all tests: 2.1 GB. Using `--git-aware` option: 460 MB. 
The .git folder contains a lot of cruft!

### Checklist
- [x] Pull request details were added to HISTORY.rst

### CODE REVIEW

**Comment by rhpvorderman** [comment]
Fixes #78 and #125

**Comment by Redmar-van-den-Berg** [comment]
I like the idea of skipping `.git`, since I can't imagine many people using files from that folder in their tests. Although it might be better to make it more general, i.e. add an option to skip hidden files and folder, instead of only `.git`. That way we make no assumptions about people using git (and .gitignore, which I'm always lazy about :wink:)

I would also be in favour of just enabling this by default, and maybe including a message to the user that hidden files and folders are skipped, to make sure it doesn't catch people of guard.

**Comment by rhpvorderman** [comment]
> I like the idea of skipping .git, since I can't imagine many people using files from that folder in their tests. Although it might be better to make it more general, i.e. add an option to skip hidden files and folder, instead of only .git. That way we make no assumptions about people using git (and .gitignore, which I'm always lazy about wink)

This does not strictly need .gitignore. It only copies files checked in with git. It uses `git ls-files --recurse-submodules` internally.

This has an enormous advantage over only skipping hidden files. When you run the workflow in the directory itself for a quick test, it creates an enormous amount of non-hidden files. These will be copied by default and influence your results. With `--git-aware` this does not happen anymore.

> I would also be in favour of just enabling this by default, and maybe including a message to the user that hidden files and folders are skipped, to make sure it doesn't catch people of guard.

I am also in favour of enabling many options by default. Such as `--keep-workflow-wd-on-fail`, `--symlink` and `--git-aware` but that would change the default behaviour. Which is not nice to people who depend on this project. It is not just us anymore ;-). 
I do emit a warning though when a `.git` folder is detected, but `--git-aware` is not enabled. 

If you want some default options you can add a `pytest.ini` file to your repository with said options. [More details here](https://docs.pytest.org/en/4.6.x/reference.html#ini-options-ref). 
As a matter of fact, that should probably be in the pytest-workflow-docs as well. Since I am adding quite a lot of options all the time.

**Comment by rhpvorderman** [comment]
> Although it might be better to make it more general, i.e. add an option to skip hidden files and folder, instead of only .git

I agree this might be better. But it is harder to implement and also harder for the user to use. I will have to implement complicated matching patterns etc. And the user has to provide these patterns.

`git ls-files` arguably does a great job selecting only relevant files. If it's not added with `git add` it is not considered part of the files worth it to be copied. This makes pytest-workflow extremely useful in a version controlled workflow repository. Since 99% of the version control is done in git, this provides good synergy for most of the users who use their workflows with version control.

**Review by DavyCats — APPROVED** [review]

**Pull request merged**
