### PR TITLE
Make pytest_collect_file() compatible with pytest 8.1+

### PR DESCRIPTION
**Pull request by JAlvarezJarreta**
### Checklist
- [X] Pull request details were added to HISTORY.rst

### CODE REVIEW

**Comment by rhpvorderman** [comment]
Thanks for the patch!

8.0+ already. When I started it was version 3.0. It seems like they love breaking everyone's stuff every year... 

I will put this on my todo list for this week. Looks like python3.7 breaks as well. As that is not supported I will remove support and make sure the CI passes on this one.

**Comment by rhpvorderman** [comment]
Looks like a change that was implemented in 7.0.0. Unfortunately I got no deprecation warnings for this one. I will merge this right away and make a separate PR for 3.12 addition and 3.7 removal.

**Comment by JAlvarezJarreta** [comment]
Yes, `pytest` seems to be following `SQLAlchemy` practices on making breaking changes in subversions... :see_no_evil: Thank you for reviewing and adding this so quickly!

**Comment by rhpvorderman** [comment]
@JAlvarezJarreta The new version is released on PyPI now. I am sorry it took so long!

**Comment by JAlvarezJarreta** [comment]
Thank you @rhpvorderman!

**Pull request merged**
